version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - '9092:9092'
      - '29092:29092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: LISTENER_DOCKER://broker:29092,LISTENER_EXT://broker:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER://broker:29092,LISTENER_EXT://broker:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER:PLAINTEXT,LISTENER_EXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  postgres1:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  app1:
    image: banking-simulator1-img
    ports:
      - '8081:8080'

  postgres2:
    image: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  app2:
    image: banking-simulator2-img
    ports:
      - '8082:8080'

  postgres3:
    image: postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  app3:
    image: banking-simulator3-img
    ports:
      - '8083:8080'