version: '3'
services:
  postgres3:
    image: postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  app3:
    image: banking-simulator3-img
    ports:
      - '8082:8080'