 version: '3'
 services:
   postgres:
     image: postgres
     environment:
       POSTGRES_PASSWORD: mysecretpassword
     ports:
       - '5436:5432'


#docker run -d --name bank-simulator -e POSTGRES_PASSWORD=mysecretpassword -p 5436:5432 postgres
