# version: '3'
# services:
#   db:
#     image: postgres
#     environment:
#       POSTGRES_USER: postgres1
#       POSTGRES_PASSWORD: mysecretpassword
#     ports:
#       - '5436:5432'
#     volumes:
#       - db:/var/lib/postgresql/data
# volumes:
#   db:
#     driver: local


#docker run -d --name bank-simulator -e POSTGRES_PASSWORD=mysecretpassword -p 5436:5432 postgres
