version: '3'
services:
  postgres1:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  app1:
    image: banking-simulator1-img
    ports:
      - '8080:8080'