version: '3'
services:
  postgres2:
    image: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  app2:
    image: banking-simulator2-img
    ports:
      - '8081:8080'